name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 24 hours at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Install Chrome & WebDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Verify POM.xml Exists
        run: |
          cd Testt
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found in $(pwd)."
            exit 1
          fi

      - name: Run Selenium Tests in Headless Mode
        run: |
          cd Testt
          mvn clean test -Dwebdriver.chrome.args="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage"

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports
          path: Testt/target/surefire-reports/
